### ISSUE TITLE
Cannot compile on linux

### ISSUE THREAD

**Issue by frdescam** [divinepet/ft_containers-unit-test#3]
Hello!
I'm trying to run your tester on linux and i always get this error that i can't fix even on the 42's Xubuntu VM 

![image](https://user-images.githubusercontent.com/58341994/144705473-7fb08a0c-ca32-464b-9e17-5f0f38c5dee2.png)

Is your tester supposed to be run only on mac? or is there some workaround to make it compile on linux?

**Comment by divinepet** [comment]
@frdescam
hi! thank you for your issue.
unfortunately, we still can't ensure compatibility between tester and linux OS, but if you have only this error, i can suggest you comment this lines:
https://github.com/divinepet/ft_containers-unit-test/blob/main/sources/system/run_set.cpp#L32
https://github.com/divinepet/ft_containers-unit-test/blob/main/sources/system/run_map.cpp#L35
and remove this file from project:
https://github.com/divinepet/ft_containers-unit-test/blob/main/sources/system/Alloc.hpp

**Comment by frdescam** [comment]
@divinepet 
Hi! thank you! It worked, i just had to do some changes in addition to yours:

- comment https://github.com/divinepet/ft_containers-unit-test/blob/main/sources/system/lib.hpp#L24
- add 
```
+#include <string.h>
+#include <sys/wait.h>
```
to https://github.com/divinepet/ft_containers-unit-test/blob/main/sources/system/engine.ipp

and it seems to work well
